language: cpp
#  - clang
  - gcc
before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq
install:
 # install g++ 4.8, if tests are run with g++
    - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi

    - if [ "$CXX" == "clang++" ]; then cwd=$(pwd); fi

    # Install libc++ if tests are run with clang++
    - if [ "$CXX" == "clang++" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk@181765 libcxx; fi
    - if [ "$CXX" == "clang++" ]; then cd libcxx/lib && bash buildit; fi
    - if [ "$CXX" == "clang++" ]; then sudo cp ./libc++.so.1.0 /usr/lib/; fi
    - if [ "$CXX" == "clang++" ]; then sudo mkdir -p /usr/include/c++/v1; fi
    - if [ "$CXX" == "clang++" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
    - if [ "$CXX" == "clang++" ]; then cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so; fi
    - if [ "$CXX" == "clang++" ]; then sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd; fi

    - if [ "$CXX" == "clang++" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxxabi/trunk@181765 libcxx; fi
    - if [ "$CXX" == "clang++" ]; then cd libcxxabi/lib && bash buildit; fi
    - if [ "$CXX" == "clang++" ]; then sudo cp ./libc++abi.so.1.0 /usr/lib/; fi
    - if [ "$CXX" == "clang++" ]; then sudo mkdir -p /usr/include/c++/v1; fi
    - if [ "$CXX" == "clang++" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
    - if [ "$CXX" == "clang++" ]; then cd /usr/lib && sudo ln -sf libc++abi.so.1.0 libc++abi.so; fi
    - if [ "$CXX" == "clang++" ]; then sudo ln -sf libc++abi.so.1.0 libc++abi.so.1 && cd $cwd; fi

# # libc++ for c++11
#     - cwd=$(pwd)
#     - svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx
#     - cd libcxx/lib && bash buildit
#     - sudo cp ./libc++.so.1.0 /usr/lib/
#     - sudo mkdir -p /usr/include/c++/v1
#     - cd .. && sudo cp -r include/* /usr/include/c++/v1/
#     - cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so
#     - sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd
# # libc++abi
#     - cwd=$(pwd)
#     - svn co --quiet http://llvm.org/svn/llvm-project/libcxxabi/trunk libcxxabi
#     - cd libcxxabi/lib && bash buildit
#     - sudo cp ./libc++abi.so.1.0 /usr/lib/
#     - sudo mkdir -p /usr/include/c++/v1
#     - cd .. && sudo cp -r include/* /usr/include/c++/v1/
#     - cd /usr/lib && sudo ln -sf libc++abi.so.1.0 libc++abi.so
#     - sudo ln -sf libc++abi.so.1.0 libc++abi.so.1 && cd $cwd
# required x11 and opengl libs
    - sudo apt-get -qq install xorg-dev
    - sudo apt-get -qq install libglu1-mesa-dev
# cmake
    - sudo apt-get -qq install cmake
script: ./configure && make -C build

