language: cpp
compiler: clang
before_install:
    - sudo apt-get install --allow-unauthenticated -qq clang-3.4
    - svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx
    - cd libcxx/lib && bash buildit
    - sudo cp ./libc++.so.1.0 /usr/lib/
    - sudo mkdir /usr/include/c++/v1
    - cd .. && sudo cp -r include/* /usr/include/c++/v1/
    - cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so
    - sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd
    - export CXX="clang++-3.4"
# required x11 and opengl libs
    - sudo apt-get -qq install xorg-dev
    - sudo apt-get -qq install libglu1-mesa-dev
# cmake
    - sudo apt-get -qq install cmake
script: ./configure && make -C build

